# Client port of 4222 on all interfaces
port: 4222

# HTTP monitoring port
monitor_port: 8222

# Enabling JetStream
jetstream: enabled

# In lame duck mode the server rejects new clients and slowly closes client
# connections. After this duration is over the server shuts down.
# Set this to the stop duration for ECS tasks.
lame_duck_duration: 30s

# Creates the SYS account and designates it as the NATS system account.
# When running any "nats server" commands add the arguments:
# --user admin --password pass 
accounts: {
  SYS: { 
    users: [
      {user: admin, password: pass}
    ],
  },
}
system_account: SYS


# This is for clustering multiple servers together.
cluster {
  # It is recommended to set a cluster name
  name: "backend"

  # Route connections to be received on any interface on port 6222
  port: 6222

  # Duration at which pings are sent to clients, leaf nodes and routes.
  ping_interval: 5s
  
  # How many unanswered pings the server will allow before closing the
  # connection.
  ping_max: 2

  # List of servers to cluster with. All nodes in the cluster are discovred 
  # via gossiping. 
  routes: [nats://nats-dynamic:6222]

  # The number of route connections between two servers in a cluster. Currently
  # disabled as the feature does not work with NATS being scaled dynamically in 
  # Docker. See isssue raised: https://github.com/nats-io/nats.go/issues/2028. 
  pool_size: -1
}
