services: 
  consumer:
    scale: 1
    build:
      context: ./src
      dockerfile: Dockerfile
      args:
        GO_MAIN_PACKAGE: consumer
    environment:
      CONSUMER_NUM: 150
    restart: always
    depends_on: 
      - nats-dynamic

  publisher:
    scale: 1
    build:
      context: ./src
      dockerfile: Dockerfile
      args:
        GO_MAIN_PACKAGE: publisher
    environment:
      PUBLISHER_NUM: 10
    restart: always
    depends_on: 
      - nats-dynamic

  nats-dynamic: 
    command: "/bin/sh -c 'nats-server -c /etc/nats/nats-server.conf -server_name $${HOSTNAME}'"
    # scale: 3
    domainname: nats
    stop_grace_period: 45s
    build: 
      context: ./nats
    ports:
      - "4222-4232:4222"
    environment:
      STREAM_REPLICAS: 3
      STREAM_NAME: "event_stream"
      STREAM_SUBJECT: "event.>"

