services: 
  consumer:
    scale: 1
    build:
      context: ./src
      dockerfile: Dockerfile
      args:
        GO_MAIN_PACKAGE: consumer
    environment:
      CONSUMER_NUM: 100
    restart: always

  publisher:
    scale: 1
    build:
      context: ./src
      dockerfile: Dockerfile
      args:
        GO_MAIN_PACKAGE: publisher
    environment:
      PUBLISHER_NUM: 100
    restart: always

  nats-dynamic: 
    command: "/bin/sh -c 'nats-server -D -cluster_name local -cluster nats://0.0.0.0:6222 -routes nats://nats-dynamic:6222 -js -server_name $${HOSTNAME}'"
    scale: 3
    domainname: nats
    build: 
      context: ./nats
    ports:
      - "4222-4232:4222"
    environment:
      JS_STREAM_REPLICAS: 3
    profiles: ["dynamic"]
    depends_on:
      - consumer
      - publisher

  nats-static-1:
    container_name: nats-static-1
    command: nats-server -cluster_name local -cluster nats://0.0.0.0:6222 -js -routes nats://nats-static-1:6222 -server_name nats-static-1
    build:
      context: ./nats
    ports:
      - "4222:4222"
    environment:
      JS_STREAM_REPLICAS: 3
    depends_on:
      - consumer
      - publisher
    profiles: ["static"]

  nats-static-2: 
    container_name: nats-static-2
    command: nats-server -cluster_name local -cluster nats://0.0.0.0:6222 -routes nats://nats-static-1:6222 -js -server_name nats-static-2
    build:
      context: ./nats
    environment:
      JS_STREAM_REPLICAS: 3
    depends_on:
      - nats-static-1
    profiles: ["static"]

  nats-static-3:
    container_name: nats-static-3
    command: nats-server -cluster_name local -cluster nats://0.0.0.0:6222 -routes nats://nats-static-1:6222 -js -server_name nats-static-3
    build:
      context: ./nats
    environment:
      JS_STREAM_REPLICAS: 3
    depends_on:
      - nats-static-1
    profiles: ["static"]
